

SELECT COUNT(ID)
FROM HEAVY_WEAPONES
WHERE SPID IN (SELECT SPID
                FROM PRODUCT_SUBCATEGORY
                WHERE (SUPPLIER LIKE '%US%' OR SUPPLIER LIKE '%us%'
                 OR SUPPLIER LIKE '%ussr%' OR SUPPLIER LIKE '%USSR%'
                 OR SUPPLIER LIKE '%russia%' OR SUPPLIER LIKE '%RUSIIA%')) 

